### ISSUE TITLE
Crash on registration

### ISSUE THREAD

**Issue by Efimero** [tmetcalfe89/JsonifyCraft-1.14#1]
Tried loading with just a block with name Custom, got this:
https://gist.github.com/Efimero/94cdd8f575434ae4bcb8c7c7f9202713
`net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: jsonifycraft:Custom`
seems like you don't want to pass the modid in 1.14?

**Comment by tmetcalfe89-zz** [comment]
Registry names can't have capital letters. Rename it to `custom` and let me know if that solves the problem.

**Comment by Efimero** [comment]
huh, ok
maybe add a check on your mod so the error is informative and closes the server instead of crashing

**Comment by tmetcalfe89-zz** [comment]
I'll take it into consideration. Given the nature of this solution, and the fact that I'm the only dev, I'm depending more on the wiki that I'm writing up. Maybe a compromise that prompts the user to visit the wiki, or the issue tracker/discord if that doesn't work. Thanks for your report!
